# Generated by Django 4.1.4 on 2024-04-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='guests',
            field=models.IntegerField(default=0),
        ),
    ]
